### ISSUE TITLE
Error in NPM

### ISSUE THREAD

**Issue by okq550** [microservices-patterns/ftgo-application#31]
Got the following error after running docker-compose up -d

` docker-compose up -d
Creating network "ftgo-application_default" with the default driver
Building ftgo-api-gateway-graphql
Step 1/7 : FROM node:9.11.2-alpine
 ---> a56170f59699
Step 2/7 : COPY package.json .
 ---> Using cache
 ---> 481bb34738e9
Step 3/7 : RUN npm install
 ---> Using cache
 ---> b13294e828f9
Step 4/7 : COPY tsconfig.json .
 ---> Using cache
 ---> 2df4e386e2d4
Step 5/7 : ADD src ./src
 ---> Using cache
 ---> 4ce1265636fa
Step 6/7 : RUN npm run build
 ---> Running in 7fe037457ce3

> @ build /
> tsc

node_modules/apollo-utilities/lib/util/mergeDeep.d.ts(2,52): error TS2370: A rest parameter must be of an array type.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-17T15_48_54_295Z-debug.log
ERROR: Service 'ftgo-api-gateway-graphql' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 2`

**Comment by cer** [comment]
@okq550 Sorry about that. I'd fixed this problem in a branch but not in master. I just pushed a change.

**Comment by nililee** [comment]
Hi, Chris
I am still have the same problem as follows:

> @ build /                                                                                                                                                                                                > tsc                                                                                                                                                                                                                                                                                                                                                                                                                 node_modules/apollo-link/lib/types.d.ts(2,30): error TS7016: Could not find a declaration file for module 'graphql/language/ast'. '/node_modules/graphql/language/ast.js' implicitly has an 'any' type.      Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql/language/ast';`                                                                  node_modules/apollo-link/lib/types.d.ts(3,33): error TS7016: Could not find a declaration file for module 'graphql/execution/execute'. '/node_modules/graphql/execution/execute.js' implicitly has an 'any' type.                                                                                                                                                                                                       Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql/execution/execute';`                                                             node_modules/apollo-utilities/lib/directives.d.ts(1,85): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.                Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/apollo-utilities/lib/fragments.d.ts(1,30): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.                 Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/apollo-utilities/lib/getFromAST.d.ts(1,79): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.                Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/apollo-utilities/lib/storeUtils.d.ts(1,192): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.               Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/apollo-utilities/lib/transform.d.ts(1,127): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.                Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/apollo-utilities/lib/util/errorHandling.d.ts(1,33): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.        Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/graphql-tools/dist/Interfaces.d.ts(1,190): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.                 Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/graphql-tools/dist/mock.d.ts(1,86): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.                        Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/graphql-tools/dist/schemaGenerator.d.ts(1,103): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.            Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/graphql-tools/dist/stitching/delegateToSchema.d.ts(1,163): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.                                                                                                                                                                                                            Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/graphql-tools/dist/stitching/introspectSchema.d.ts(1,31): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.d.ts(2,68): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.                                                                                                                                                                                                   Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               node_modules/graphql-tools/dist/stitching/mergeSchemas.d.ts(1,49): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' implicitly has an 'any' type.      Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`                                                                               npm ERR! code ELIFECYCLE                                                                                                                                                                                   npm ERR! errno 2                                                                                                                                                                                           npm ERR! @ build: `tsc`                                                                                                                                                                                    npm ERR! Exit status 2                                                                                                                                                                                     npm ERR!                                                                                                                                                                                                   npm ERR! Failed at the @ build script.                                                                                                                                                                     npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                                                                                                                                                                                                    npm ERR! A complete log of this run can be found in:                                                                                                                                                       npm ERR!     /root/.npm/_logs/2019-09-04T02_11_56_764Z-debug.log                                                                                                                                           ERROR: Service 'ftgo-api-gateway-graphql' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 2

My docker version is 19.0.3 and docker-compose 1.24.1.
I don't know what caused this problem.

Pls help me.
